devnetType: docker

defaultFee: 2000
defaultStake: 10000

borChainId: 15001
heimdallChainId: heimdall-15001

borDockerBuildContext: '../../bor'
heimdallDockerBuildContext: 'https://github.com/maticnetwork/heimdall.git#develop'

genesisContractsBranch: master
contractsBranch: mardizzone/node-16

blockTime:
  - '2'
blockNumber:
  - '0'

sprintSize:
  - '64'
sprintSizeBlockNumber:
  - '0'

numOfBorValidators: 3
numOfBorSentries: 0
numOfBorArchiveNodes: 0

devnetBorFlags: config,config,config

numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0

ethURL: http://ganache:9545
ethHostUser: ubuntu
