# defaultStake: 10000
# defaultFee: 2000
# borChainId: "15001"
# heimdallChainId: heimdall-15001
# contractsBranch: jc/v0.3.1-backport
# sprintSize: 64
# blockNumber: '0'
# blockTime: '2'
# numOfValidators: 3
# numOfNonValidators: 0
# ethURL: http://ganache:9545
# ethHostUser: ubuntu
# devnetType: docker
# borDockerBuildContext: "../../bor"
# heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"


defaultStake: 10000
defaultFee: 2000
borChainId: 15001
heimdallChainId: heimdall-4052
contractsBranch: 2ed59de3641c407c64def1b40bcd090cb9cc048a
genesisContractsBranch: master
sprintSize:
  - '64'
blockNumber:
  - '0'
blockTime:
  - '2'
numOfValidators: 3
numOfNonValidators: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "../../bor"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
sprintSizeBlockNumber:
  - '0'
numOfArchiveNodes: 0