polygon_pos_package:
  participants:
    # 3 validators on develop branch
    # - kind: validator
    #   cl_type: heimdall-v2
    #   cl_image: heimdall-v2:develop
    #   el_type: bor
    #   el_image: bor:develop
    #   count: 3
    #   el_bor_produce_witness: false
    #   el_bor_sync_with_witness: false

    # 3 validators on stateless_sync branch
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 3
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false

    # 3 total RPC nodes
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false

    # Stateless RPC node
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true

  additional_services:
    - prometheus_grafana
    - test_runner
