polygon_pos_package:
  participants:
    # 1 validator on Bor's develop branch
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:develop
      count: 1
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

    # 5 validators on Bor's stateless_sync branch
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 5
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false

    # 3 Total RPC nodes on Bor's stateless_sync branch
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false

    # 1 Stateless RPC node
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:stateless_sync
      el_type: bor
      el_image: bor:stateless_sync
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true

  additional_services:
    - prometheus_grafana
    - test_runner
