# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/apilayer/freegeoip"

[[constraint]]
  name = "github.com/cespare/cp"
  version = "0.1.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.5.4"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  branch = "master"
  name = "github.com/karalabe/usb"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mohae/deepcopy"

[[constraint]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/steakknife/bloomfilter"

[[constraint]]
  name = "github.com/tyler-smith/go-bip39"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/wsddn/go-ecdh"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/natefinch/npipe.v2"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
