name: kurtosis-pre-run
description: Prepare the environment for deploying Kurtosis packages.

runs:
  using: composite
  steps:
    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install -y kurtosis-cli=1.7.2
        kurtosis analytics disable
        kurtosis version

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.0.0
