version: "3.3"
volumes:
  grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: bor-prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 127.0.0.1:9091:9090
  grafana:
    image: grafana/grafana
    network_mode: host
    container_name: bor-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 127.0.0.1:3001:3000
