name: Docker Images For Latest Branches

on:
  push:
    branches:
      - v1.10.4-upgrade

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        set -x
        ls -l
        echo "Docker login"
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo "Running build"
        docker build -t maticnetwork/bor:v1.10.4-upgrade .
        echo "Pushing image"
        docker push maticnetwork/bor:v1.10.4-upgrade
        echo "Done"
